apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 2  # Tres réplicas para HA
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          value: "my_secret_cookie"  # Necesario para el clúster
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        - name: RABBITMQ_NODENAME
          value: "rabbit@$(MY_POD_NAME).rabbitmq.default.svc.cluster.local"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command: ["/bin/sh", "-c"]
        args:
          - export RABBITMQ_NODENAME="rabbit@$(MY_POD_NAME).rabbitmq.default.svc.cluster.local"; 
            exec docker-entrypoint.sh rabbitmq-server
        resources:
          requests:
            memory: "256Mi"  # Reducir memoria mínima
            cpu: "100m"      # Reducir CPU mínima
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        volumeMounts:
        - name: rabbitmq-storage
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
