name: Deploy Application to custom runner

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          docker compose down || true
          docker compose up --build -d
